self:
  1:
    - 'ねむいにゃあ'
    - 'にゃあにゃあにゃあ'
    - '元気にゃー？'
    - '今日一日頑張るにゃー'
    - 'にゃー'
    - 'これからよろしくにゃー'
    - '仲良くするにゃー'
    - 'ほにゃあ'
    - '遊びにいきたいにゃー'
    - 'でかけてくるにゃー'
  2:
    - 'にゃめるにゃー'
    - '昨日はなにしかにゃあ...'
    - '明日はなにしようかにゃあ'
    - '眠くなってきたにゃあ'
    - 'にゃにゃにゃあ'
    - 'にゃあーん'
    - 'にゃっ'
    - '我輩は猫であるにゃ'
    - '今日は暖かいにゃあ'
    - 'ごろにゃん'
  3:
    - '最近友達ができたにゃあ'
    - '仲良くするにゃあ'
    - 'にゃるほど。。。'
    - 'にゃむにゃむ'
    - 'にゃあああああああああああああああ'
    - '今のご飯まずいにゃー。美味しいのにするにゃー。'
    - '明日は晴れな気がするにゃあ'
    - 'にゃにゅにゅ。。。'
    - 'ひなたぼっこしたいにゃあ'
    - 'にゃおん'
  4:
    - '最近は平和だにゃあ'
    - 'にゃ？'
    - 'どうしたにゃ？'
    - '今日は眠たいにゃー。'
    - 'そろそろ遊んでやるにゃ^^'
    - 'もう寝なくていいのかにゃ？'
    - 'にゃふふふふふふふふふ'
    - 'にゃみだが止まらないにゃ'
    - 'にゃろう...'
    - 'この前遊びに行ったところは楽しかったにゃ♪'
  5:
    - '遊ぼうにゃー'
    - '構うにゃー'
    - '今日はにゃにしたにゃあ？'
    - 'にゃににゅねにょー'
    - '昨日犬に追っかけられたにゃー...'
    - '明日は雨が振る気がするにゃ。。。気のせいにゃ。'
    - 'にゃったー！！！'
    - '今日のあたしはかわいいにゃ！'
    - 'にゃらの鹿はかわいいにゃ///'
    - 'みちょぱ'
  6:
    - 'にゃにゃにゃにゃにゃにゃにゃにゃにゃんにゃんにゃにゃん！'
    - 'にゃんぱー！'
    - '肉球は前には5つあるけど後ろには4つしかにゃいにゃ！'
    - '僕達はタウリンをとらにゃか失明しちゃうにゃ...'
    - '寝てたらパンチしてやるにゃ。'
    - '肉球触るにゃ〜'
    - 'AB型のねこって全然いないんだにゃー。'
    - 'もふもふしてやるにゃ'
    - '最近あんまり寝れないにゃあ'
    - 'にゃむう。。。'
  7:
    - 'にゃにしてるにゃー？'
    - 'にゃにゃあ？'
    - '古代エジプト人に深く愛されていたにゃ！'
    - '暗いところでも良く見えるにゃー。'
    - '本気をだせばボルトより早く走れるにゃ♪'
    - '身長の5倍は飛ぶことができるにゃ。'
    - 'イングランドでは「猫が耳の後ろを洗うと雨が降る」という言い伝えがあるにゃ！'
    - 'まーたたびいいいいいいいいいいいいいい'
    - '近所の猫がかわいいにゃあ'
    - 'にゃっふん！'
  8:
    - 'にゃおーん'
    - '今日はにゃにするにゃー？'
    - '構うにゃー！'
    - 'にゃふんっ'
    - 'バステト様はあたしたちの神様にゃ！'
    - 'ごろごろするのが好きにゃんだにゃ〜'
    - 'にゃにゃにゃにゃんにゃんにゃんにゃんにゃんにゃんにゃんｎにゃんにゃんにゃーん！'
    - '一緒に寝るにゃあ'
    - 'みゃーお'
    - '最近毛並みが綺麗だにゃあ。。。'
  9:
    - 'お魚食べたいにゃあ❤'
    - 'にゃおーん❤'
    - '遊びにいきたいにゃあ。。。'
    - '今日いいことがあったにゃあ.。o○'
    - '明日も頑張るにゃ！'
    - 'にゃむにゃむ...'
    - 'にゃあ(しっぽふりふり)'
    - 'ニャンダふる！'
    - 'ふにゃあ'
    - '今日もいい天気にゃん'
  10:
    - '大好きにゃん'
    - 'にゃにゃにゃー❤'
    - '遊ぼうにゃん♪'
    - 'にゃまむぎにゃまごめにゃまたまご〜'
    - '愛してるにゃん❤'
    - 'むにゃあ。。。'
    - 'あーそーぶーにゃー！'
    - 'もう長い付き合いにゃ！'
    - 'いつもありがとにゃん❤'
    - 'にゃにゃにゃんにゃん♪'
